# Generated by Django 4.1 on 2022-08-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='invoice_details',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('d_name', models.CharField(max_length=40)),
                ('d_email', models.CharField(max_length=40)),
                ('d_phone', models.IntegerField()),
                ('d_address', models.CharField(max_length=50)),
                ('d_items', models.TextField()),
                ('d_catagoried', models.TextField()),
                ('d_prices', models.TextField()),
                ('d_quantities', models.TextField()),
            ],
        ),
    ]
